### ISSUE TITLE
Add output option for the zarr name

### ISSUE THREAD

**Issue by joshmoore** [weso/RemoteHDT#2]
`./remote-hdt_v0.0.7_aarch64_apple --rdf resources/1-lubm.ttl --serialize`
currently outputs to `root.zarr`.

Note also if the output directory exists the error is non-informative:
`Error: "Error creating the File System Store"` (At least it doesn't overwrite :smile:)

**Comment by angelip2303** [comment]
You already can change the name of the Zarr directory by using the `--zar` or `-z` option. In the example you provided you could do it as follows: `./remote-hdt_v0.0.7_aarch64_apple --rdf resources/1-lubm.ttl --serialize --zarr 1-LUBM.zarr`.

Regarding the non-informative errors, it is true that errors in general should be improved, the descriptions they provide, but I have changed the error for that exact case. Currentyl, the error message is as follows: `The Path already exists, please provide an empty path`.
