### ISSUE TITLE
Makes choice of benchmark (1-, 10-, 100-) a parameter

### ISSUE THREAD

**Issue by joshmoore** [weso/RemoteHDT#3]
Rather than needing to update the code.

**Comment by angelip2303** [comment]
By executing `cargo run --release --example <example_name> <number_of_universities>` you can generate the `.zarr` directory for the requested size.

**Comment by joshmoore** [comment]
Just so I understand, this was already possible before or you added it?

**Comment by angelip2303** [comment]
I have just added it :D

**Comment by joshmoore** [comment]
❤️ (If you reference the issue from the commit/PR, I'll know 😉)
